### ISSUE TITLE
Fetching secured Images

### ISSUE THREAD

**Issue by gauravsaini03** [chafey/cornerstoneWebImageLoader#3]
Hello,

I am unable to set Authorization headers, as the images which are fetched are secured and giving 401.

Thanks
Gaurav

**Comment by Ethoxyethaan** [comment]
Set 
image.crossOrigin = 'anonymous';
to 
image.crossOrigin = 'use-credentials';

in cornerstoneWebImageLoader.js

**Comment by chafey** [comment]
I just modified cornerstoneWebImageLoader to use XHR to load images and included a mechanism to configure a beforeSend callback so you can modify XHR as needed (e.g. to add auth headers).  See the example on how to use this.

Please close this issue if it meets your needs

**Comment by Ethoxyethaan** [comment]
Chafey

I think the Image() constructor does not respect the Same-origin policy however xmlhttprequest does. (unless server permits it ... with the needed configuration changes.)

Am i allowed to suggest a duo solution, or am i missing out on some information?

**Comment by chafey** [comment]
You are free to suggest anything!  Are you saying that you need the less secure CORS bypassing feature of Image()?

**Comment by Ethoxyethaan** [comment]
Personally: no, I use a reverse proxy for the collection of image resources because we want to audit and control everything that happens on top of the vendor provided image archives.

In the past I've seen Image() being used to bypass same-origin policy for viewing server side rendered dicom, I'd figure other people would like to make use of it too.

Anyway perhaps this is outside the scope of this small plugin. I'll suggest a patch that allows the unsafe Image() constructor in parallel with the xmlhttprequest and lets see if people like it or not.

**Comment by chafey** [comment]
Personally I think the library should default to safe and secure behavior and should not use Image() at all.  If someone wants to bypass CORS, they can make their own image loader.  

Please don't feel guilty at all - the fact that it is being used and people appreciate it is highly satisfying.  I hope you can find time to contribute in the future so you can experience the same satisfaction I do!
